create extension if not exists pgcrypto;
create type public.user_role as enum ('admin','caixa','estoque');
create type public.stock_movement_type as enum ('entrada','saida','venda','ajuste','perda','devolucao','cancelamento');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null, role user_role not null default 'caixa', created_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), name text not null unique, created_at timestamptz not null default now());
create table public.suppliers (id uuid primary key default gen_random_uuid(), name text not null, document text, phone text, email text, address text, created_at timestamptz not null default now());
create table public.products (id uuid primary key default gen_random_uuid(), sku text not null unique, barcode text unique, name text not null, description text, category_id uuid references categories(id), supplier_id uuid references suppliers(id), unit text not null, minimum_stock numeric not null default 0 check (minimum_stock >= 0), price numeric(12,2) not null check (price >= 0), cost numeric(12,2) not null default 0 check (cost >= 0), stock numeric not null default 0 check (stock >= 0), active boolean not null default true, created_by uuid references profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.product_batches (id uuid primary key default gen_random_uuid(), product_id uuid not null references products(id), batch_code text not null, quantity numeric not null check (quantity >= 0), expires_on date, supplier_id uuid references suppliers(id), created_at timestamptz not null default now());
create table public.stock_movements (id uuid primary key default gen_random_uuid(), product_id uuid not null references products(id), type stock_movement_type not null, quantity numeric not null check (quantity > 0), before_stock numeric not null, after_stock numeric not null, origin text not null, note text, created_by uuid references profiles(id), created_at timestamptz not null default now());
create table public.sales (id uuid primary key default gen_random_uuid(), sale_number bigint generated always as identity unique, customer_id uuid, status text not null default 'completed', subtotal numeric(12,2) not null, discount numeric(12,2) not null default 0, total numeric(12,2) not null, created_by uuid references profiles(id), cancelled_at timestamptz, cancel_reason text, created_at timestamptz not null default now());
create table public.sale_items (id uuid primary key default gen_random_uuid(), sale_id uuid not null references sales(id), product_id uuid not null references products(id), quantity numeric not null check (quantity > 0), unit_price numeric(12,2) not null, discount numeric(12,2) not null default 0);
create table public.payments (id uuid primary key default gen_random_uuid(), sale_id uuid not null references sales(id), method text not null, amount numeric(12,2) not null);
create table public.label_templates (id uuid primary key default gen_random_uuid(), name text not null, width_mm numeric not null, height_mm numeric not null, columns_count integer not null default 1, config jsonb not null default '{}'::jsonb, created_by uuid references profiles(id));
create table public.label_print_history (id uuid primary key default gen_random_uuid(), product_id uuid references products(id), template_id uuid references label_templates(id), quantity integer not null, created_by uuid references profiles(id), created_at timestamptz not null default now());
create index products_name_idx on products using gin (to_tsvector('simple', name));
create index products_category_idx on products(category_id); create index stock_movements_product_idx on stock_movements(product_id, created_at desc); create index sales_created_idx on sales(created_at desc);

alter table profiles enable row level security; alter table categories enable row level security; alter table suppliers enable row level security; alter table products enable row level security; alter table product_batches enable row level security; alter table stock_movements enable row level security; alter table sales enable row level security; alter table sale_items enable row level security; alter table payments enable row level security; alter table label_templates enable row level security; alter table label_print_history enable row level security;
create or replace function public.get_current_role() returns user_role language sql stable security definer set search_path = public as $$ select role from profiles where id = auth.uid() $$;
create policy authenticated_read_products on products for select to authenticated using (true);
create policy staff_manage_products on products for all to authenticated using (public.get_current_role() in ('admin','estoque')) with check (public.get_current_role() in ('admin','estoque'));
create policy staff_read_business_data on stock_movements for select to authenticated using (public.get_current_role() in ('admin','estoque','caixa'));
-- Vendas e baixa de estoque devem usar RPC transacional com bloqueio da linha do produto.
